SELECT
    *
    ,AVG(active_quarter) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS active_quarter_avg_6
    ,AVG(cliente_vip) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cliente_vip_avg_6
    ,AVG(internet) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS internet_avg_6
    ,AVG(cliente_edad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cliente_edad_avg_6
    ,AVG(cliente_antiguedad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cliente_antiguedad_avg_6
    ,AVG(mrentabilidad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mrentabilidad_avg_6
    ,AVG(mrentabilidad_annual) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mrentabilidad_annual_avg_6
    ,AVG(mcomisiones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcomisiones_avg_6
    ,AVG(mactivos_margen) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mactivos_margen_avg_6
    ,AVG(mpasivos_margen) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpasivos_margen_avg_6
     ,AVG(cproductos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cproductos_avg_6
     ,AVG(tcuentas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS tcuentas_avg_6
     ,AVG(ccuenta_corriente) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccuenta_corriente_avg_6
     ,AVG(mcuenta_corriente_adicional) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuenta_corriente_adicional_avg_6
     ,AVG(mcuenta_corriente) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuenta_corriente_avg_6
     ,AVG(ccaja_ahorro) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccaja_ahorro_avg_6
     ,AVG(mcaja_ahorro) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_avg_6
     ,AVG(mcaja_ahorro_adicional) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_adicional_avg_6
     ,AVG(mcaja_ahorro_dolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_dolares_avg_6
     ,AVG(cdescubierto_preacordado) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cdescubierto_preacordado_avg_6
     ,AVG(mcuentas_saldo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuentas_saldo_avg_6
     ,AVG(ctarjeta_debito) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_debito_avg_6
     ,AVG(ctarjeta_debito_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_debito_transacciones_avg_6
     ,AVG(mautoservicio) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mautoservicio_avg_6
     ,AVG(ctarjeta_visa) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_avg_6
     ,AVG(ctarjeta_visa_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_transacciones_avg_6
     ,AVG(mtarjeta_visa_consumo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_visa_consumo_avg_6
     ,AVG(ctarjeta_master) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_avg_6
     ,AVG(ctarjeta_master_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_transacciones_avg_6
     ,AVG(mtarjeta_master_consumo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_master_consumo_avg_6
     ,AVG(cprestamos_personales) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cprestamos_personales_avg_6
     ,AVG(mprestamos_personales) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mprestamos_personales_avg_6
     ,AVG(cprestamos_prendarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cprestamos_prendarios_avg_6
     ,AVG(mprestamos_prendarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mprestamos_prendarios_avg_6
     ,AVG(cprestamos_hipotecarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cprestamos_hipotecarios_avg_6
     ,AVG(mprestamos_hipotecarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mprestamos_hipotecarios_avg_6
     ,AVG(cplazo_fijo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cplazo_fijo_avg_6
     ,AVG(mplazo_fijo_dolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mplazo_fijo_dolares_avg_6
     ,AVG(mplazo_fijo_pesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mplazo_fijo_pesos_avg_6
     ,AVG(cinversion1) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cinversion1_avg_6
     ,AVG(minversion1_pesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS minversion1_pesos_avg_6
     ,AVG(minversion1_dolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS minversion1_dolares_avg_6
     ,AVG(cinversion2) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cinversion2_avg_6
     ,AVG(minversion2) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS minversion2_avg_6
     ,AVG(cseguro_vida) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_vida_avg_6
     ,AVG(cseguro_auto) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_auto_avg_6
     ,AVG(cseguro_vivienda) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_vivienda_avg_6
     ,AVG(cseguro_accidentes_personales) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_accidentes_personales_avg_6
     ,AVG(ccaja_seguridad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccaja_seguridad_avg_6
     ,AVG(cpayroll_trx) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpayroll_trx_avg_6
     ,AVG(mpayroll) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpayroll_avg_6
     ,AVG(mpayroll2) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpayroll2_avg_6
     ,AVG(cpayroll2_trx) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpayroll2_trx_avg_6
     ,AVG(ccuenta_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccuenta_debitos_automaticos_avg_6
     ,AVG(mcuenta_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuenta_debitos_automaticos_avg_6
     ,AVG(ctarjeta_visa_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_debitos_automaticos_avg_6
     ,AVG(mttarjeta_visa_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mttarjeta_visa_debitos_automaticos_avg_6
     ,AVG(ctarjeta_master_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_debitos_automaticos_avg_6
     ,AVG(mttarjeta_master_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mttarjeta_master_debitos_automaticos_avg_6
     ,AVG(cpagodeservicios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpagodeservicios_avg_6
     ,AVG(mpagodeservicios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpagodeservicios_avg_6
     ,AVG(cpagomiscuentas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpagomiscuentas_avg_6
     ,AVG(mpagomiscuentas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpagomiscuentas_avg_6
     ,AVG(ccajeros_propios_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajeros_propios_descuentos_avg_6
     ,AVG(mcajeros_propios_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcajeros_propios_descuentos_avg_6
     ,AVG(ctarjeta_visa_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_descuentos_avg_6
     ,AVG(mtarjeta_visa_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_visa_descuentos_avg_6
     ,AVG(ctarjeta_master_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_descuentos_avg_6
     ,AVG(mtarjeta_master_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_master_descuentos_avg_6
     ,AVG(ccomisiones_mantenimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccomisiones_mantenimiento_avg_6
     ,AVG(mcomisiones_mantenimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcomisiones_mantenimiento_avg_6
     ,AVG(ccomisiones_otras) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccomisiones_otras_avg_6
     ,AVG(mcomisiones_otras) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcomisiones_otras_avg_6
     ,AVG(cforex) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cforex_avg_6
     ,AVG(cforex_buy) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cforex_buy_avg_6
     ,AVG(mforex_buy) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mforex_buy_avg_6
     ,AVG(cforex_sell) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cforex_sell_avg_6
     ,AVG(mforex_sell) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mforex_sell_avg_6
     ,AVG(ctransferencias_recibidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctransferencias_recibidas_avg_6
     ,AVG(mtransferencias_recibidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtransferencias_recibidas_avg_6
     ,AVG(ctransferencias_emitidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctransferencias_emitidas_avg_6
     ,AVG(mtransferencias_emitidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtransferencias_emitidas_avg_6
     ,AVG(cextraccion_autoservicio) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cextraccion_autoservicio_avg_6
     ,AVG(mextraccion_autoservicio) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mextraccion_autoservicio_avg_6
     ,AVG(ccheques_depositados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_depositados_avg_6
     ,AVG(mcheques_depositados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_depositados_avg_6
     ,AVG(ccheques_emitidos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_emitidos_avg_6
     ,AVG(mcheques_emitidos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_emitidos_avg_6
     ,AVG(ccheques_depositados_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_depositados_rechazados_avg_6
     ,AVG(mcheques_depositados_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_depositados_rechazados_avg_6
     ,AVG(ccheques_emitidos_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_emitidos_rechazados_avg_6
     ,AVG(mcheques_emitidos_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_emitidos_rechazados_avg_6
     ,AVG(tcallcenter) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS tcallcenter_avg_6
     ,AVG(ccallcenter_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccallcenter_transacciones_avg_6
     ,AVG(thomebanking) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS thomebanking_avg_6
     ,AVG(chomebanking_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS chomebanking_transacciones_avg_6
     ,AVG(ccajas_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_transacciones_avg_6
     ,AVG(ccajas_consultas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_consultas_avg_6
     ,AVG(ccajas_depositos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_depositos_avg_6
     ,AVG(ccajas_extracciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_extracciones_avg_6
     ,AVG(ccajas_otras) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_otras_avg_6
     ,AVG(catm_trx) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS catm_trx_avg_6
     ,AVG(matm) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS matm_avg_6
     ,AVG(catm_trx_other) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS catm_trx_other_avg_6
     ,AVG(matm_other) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS matm_other_avg_6
     ,AVG(ctrx_quarter) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctrx_quarter_avg_6
     ,AVG(Master_delinquency) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_delinquency_avg_6
     ,AVG(Master_status) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_status_avg_6
     ,AVG(Master_mfinanciacion_limite) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mfinanciacion_limite_avg_6
     ,AVG(Master_Fvencimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_Fvencimiento_avg_6
     ,AVG(Master_Finiciomora) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_Finiciomora_avg_6
     ,AVG(Master_msaldototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_msaldototal_avg_6
     ,AVG(Master_msaldopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_msaldopesos_avg_6
     ,AVG(Master_msaldodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_msaldodolares_avg_6
     ,AVG(Master_mconsumospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mconsumospesos_avg_6
     ,AVG(Master_mconsumosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mconsumosdolares_avg_6
     ,AVG(Master_mlimitecompra) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mlimitecompra_avg_6
     ,AVG(Master_madelantopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_madelantopesos_avg_6
     ,AVG(Master_madelantodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_madelantodolares_avg_6
     ,AVG(Master_fultimo_cierre) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_fultimo_cierre_avg_6
     ,AVG(Master_mpagado) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagado_avg_6
     ,AVG(Master_mpagospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagospesos_avg_6
     ,AVG(Master_mpagosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagosdolares_avg_6
     ,AVG(Master_fechaalta) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_fechaalta_avg_6
     ,AVG(Master_mconsumototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mconsumototal_avg_6
     ,AVG(Master_cconsumos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_cconsumos_avg_6
     ,AVG(Master_cadelantosefectivo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_cadelantosefectivo_avg_6
     ,AVG(Master_mpagominimo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagominimo_avg_6
     ,AVG(Visa_delinquency) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_delinquency_avg_6
     ,AVG(Visa_status) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_status_avg_6
     ,AVG(Visa_mfinanciacion_limite) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mfinanciacion_limite_avg_6
     ,AVG(Visa_Fvencimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_Fvencimiento_avg_6
     ,AVG(Visa_Finiciomora) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_Finiciomora_avg_6
     ,AVG(Visa_msaldototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_msaldototal_avg_6
     ,AVG(Visa_msaldopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_msaldopesos_avg_6
     ,AVG(Visa_msaldodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_msaldodolares_avg_6
     ,AVG(Visa_mconsumospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mconsumospesos_avg_6
     ,AVG(Visa_mconsumosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mconsumosdolares_avg_6
     ,AVG(Visa_mlimitecompra) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mlimitecompra_avg_6
     ,AVG(Visa_madelantopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_madelantopesos_avg_6
     ,AVG(Visa_madelantodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_madelantodolares_avg_6
     ,AVG(Visa_fultimo_cierre) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_fultimo_cierre_avg_6
     ,AVG(Visa_mpagado) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagado_avg_6
     ,AVG(Visa_mpagospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagospesos_avg_6
     ,AVG(Visa_mpagosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagosdolares_avg_6
     ,AVG(Visa_fechaalta) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_fechaalta_avg_6
     ,AVG(Visa_mconsumototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mconsumototal_avg_6
     ,AVG(Visa_cconsumos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_cconsumos_avg_6
     ,AVG(Visa_cadelantosefectivo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_cadelantosefectivo_avg_6
     ,AVG(Visa_mpagominimo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagominimo_avg_6
FROM competencia_03
