SELECT
    *
    ,AVG(active_quarter, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS active_quarter_avg_6
    ,AVG(catm_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS catm_trx_avg_6
    ,AVG(catm_trx_other, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS catm_trx_other_avg_6
    ,AVG(ccaja_ahorro, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccaja_ahorro_avg_6
    ,AVG(ccaja_seguridad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccaja_seguridad_avg_6
    ,AVG(ccajas_consultas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_consultas_avg_6
    ,AVG(ccajas_depositos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_depositos_avg_6
    ,AVG(ccajas_extracciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_extracciones_avg_6
    ,AVG(ccajas_otras, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_otras_avg_6
    ,AVG(ccajas_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajas_transacciones_avg_6
    ,AVG(ccajeros_propios_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccajeros_propios_descuentos_avg_6
    ,AVG(ccallcenter_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccallcenter_transacciones_avg_6
    ,AVG(ccheques_depositados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_depositados_avg_6
    ,AVG(ccheques_depositados_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_depositados_rechazados_avg_6
    ,AVG(ccheques_emitidos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_emitidos_avg_6
    ,AVG(ccheques_emitidos_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccheques_emitidos_rechazados_avg_6
    ,AVG(ccomisiones_mantenimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccomisiones_mantenimiento_avg_6
    ,AVG(ccomisiones_otras, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccomisiones_otras_avg_6
    ,AVG(ccuenta_corriente, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccuenta_corriente_avg_6
    ,AVG(ccuenta_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ccuenta_debitos_automaticos_avg_6
    ,AVG(cdescubierto_preacordado, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cdescubierto_preacordado_avg_6
    ,AVG(cextraccion_autoservicio, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cextraccion_autoservicio_avg_6
    ,AVG(cforex, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cforex_avg_6
    ,AVG(cforex_buy, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cforex_buy_avg_6
    ,AVG(cforex_sell, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cforex_sell_avg_6
    ,AVG(chomebanking_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS chomebanking_transacciones_avg_6
    ,AVG(cinversion1, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cinversion1_avg_6
    ,AVG(cinversion2, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cinversion2_avg_6
    ,AVG(cliente_antiguedad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cliente_antiguedad_avg_6
    ,AVG(cliente_edad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cliente_edad_avg_6
    ,AVG(cliente_vip, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cliente_vip_avg_6
    ,AVG(cmobile_app_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cmobile_app_trx_avg_6
    ,AVG(cpagodeservicios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpagodeservicios_avg_6
    ,AVG(cpagomiscuentas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpagomiscuentas_avg_6
    ,AVG(cpayroll2_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpayroll2_trx_avg_6
    ,AVG(cpayroll_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cpayroll_trx_avg_6
    ,AVG(cplazo_fijo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cplazo_fijo_avg_6
    ,AVG(cprestamos_hipotecarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cprestamos_hipotecarios_avg_6
    ,AVG(cprestamos_personales, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cprestamos_personales_avg_6
    ,AVG(cprestamos_prendarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cprestamos_prendarios_avg_6
    ,AVG(cproductos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cproductos_avg_6
    ,AVG(cseguro_accidentes_personales, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_accidentes_personales_avg_6
    ,AVG(cseguro_auto, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_auto_avg_6
    ,AVG(cseguro_vida, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_vida_avg_6
    ,AVG(cseguro_vivienda, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS cseguro_vivienda_avg_6
    ,AVG(ctarjeta_debito, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_debito_avg_6
    ,AVG(ctarjeta_debito_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_debito_transacciones_avg_6
    ,AVG(ctarjeta_master, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_avg_6
    ,AVG(ctarjeta_master_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_debitos_automaticos_avg_6
    ,AVG(ctarjeta_master_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_descuentos_avg_6
    ,AVG(ctarjeta_master_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_master_transacciones_avg_6
    ,AVG(ctarjeta_visa, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_avg_6
    ,AVG(ctarjeta_visa_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_debitos_automaticos_avg_6
    ,AVG(ctarjeta_visa_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_descuentos_avg_6
    ,AVG(ctarjeta_visa_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_transacciones_avg_6
    ,AVG(ctransferencias_emitidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctransferencias_emitidas_avg_6
    ,AVG(ctransferencias_recibidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctransferencias_recibidas_avg_6
    ,AVG(ctrx_quarter, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ctrx_quarter_avg_6
    ,AVG(internet, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS internet_avg_6
    ,AVG(mactivos_margen, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mactivos_margen_avg_6
    ,AVG(Master_cadelantosefectivo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_cadelantosefectivo_avg_6
    ,AVG(Master_cconsumos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_cconsumos_avg_6
    ,AVG(Master_delinquency, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_delinquency_avg_6
    ,AVG(Master_fechaalta, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_fechaalta_avg_6
    ,AVG(Master_Finiciomora, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_Finiciomora_avg_6
    ,AVG(Master_fultimo_cierre, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_fultimo_cierre_avg_6
    ,AVG(Master_Fvencimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_Fvencimiento_avg_6
    ,AVG(Master_madelantodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_madelantodolares_avg_6
    ,AVG(Master_madelantopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_madelantopesos_avg_6
    ,AVG(Master_mconsumosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mconsumosdolares_avg_6
    ,AVG(Master_mconsumospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mconsumospesos_avg_6
    ,AVG(Master_mconsumototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mconsumototal_avg_6
    ,AVG(Master_mfinanciacion_limite, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mfinanciacion_limite_avg_6
    ,AVG(Master_mlimitecompra, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mlimitecompra_avg_6
    ,AVG(Master_mpagado, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagado_avg_6
    ,AVG(Master_mpagominimo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagominimo_avg_6
    ,AVG(Master_mpagosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagosdolares_avg_6
    ,AVG(Master_mpagospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_mpagospesos_avg_6
    ,AVG(Master_msaldodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_msaldodolares_avg_6
    ,AVG(Master_msaldopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_msaldopesos_avg_6
    ,AVG(Master_msaldototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_msaldototal_avg_6
    ,AVG(Master_status, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Master_status_avg_6
    ,AVG(matm, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS matm_avg_6
    ,AVG(matm_other, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS matm_other_avg_6
    ,AVG(mautoservicio, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mautoservicio_avg_6
    ,AVG(mcaja_ahorro, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_avg_6
    ,AVG(mcaja_ahorro_adicional, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_adicional_avg_6
    ,AVG(mcaja_ahorro_dolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_dolares_avg_6
    ,AVG(mcajeros_propios_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcajeros_propios_descuentos_avg_6
    ,AVG(mcheques_depositados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_depositados_avg_6
    ,AVG(mcheques_depositados_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_depositados_rechazados_avg_6
    ,AVG(mcheques_emitidos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_emitidos_avg_6
    ,AVG(mcheques_emitidos_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcheques_emitidos_rechazados_avg_6
    ,AVG(mcomisiones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcomisiones_avg_6
    ,AVG(mcomisiones_mantenimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcomisiones_mantenimiento_avg_6
    ,AVG(mcomisiones_otras, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcomisiones_otras_avg_6
    ,AVG(mcuenta_corriente, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuenta_corriente_avg_6
    ,AVG(mcuenta_corriente_adicional, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuenta_corriente_adicional_avg_6
    ,AVG(mcuenta_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuenta_debitos_automaticos_avg_6
    ,AVG(mcuentas_saldo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mcuentas_saldo_avg_6
    ,AVG(mextraccion_autoservicio, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mextraccion_autoservicio_avg_6
    ,AVG(mforex_buy, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mforex_buy_avg_6
    ,AVG(mforex_sell, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mforex_sell_avg_6
    ,AVG(minversion1_dolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS minversion1_dolares_avg_6
    ,AVG(minversion1_pesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS minversion1_pesos_avg_6
    ,AVG(minversion2, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS minversion2_avg_6
    ,AVG(mpagodeservicios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpagodeservicios_avg_6
    ,AVG(mpagomiscuentas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpagomiscuentas_avg_6
    ,AVG(mpasivos_margen, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpasivos_margen_avg_6
    ,AVG(mpayroll, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpayroll_avg_6
    ,AVG(mpayroll2, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mpayroll2_avg_6
    ,AVG(mplazo_fijo_dolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mplazo_fijo_dolares_avg_6
    ,AVG(mplazo_fijo_pesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mplazo_fijo_pesos_avg_6
    ,AVG(mprestamos_hipotecarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mprestamos_hipotecarios_avg_6
    ,AVG(mprestamos_personales, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mprestamos_personales_avg_6
    ,AVG(mprestamos_prendarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mprestamos_prendarios_avg_6
    ,AVG(mrentabilidad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mrentabilidad_avg_6
    ,AVG(mrentabilidad_annual, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mrentabilidad_annual_avg_6
    ,AVG(mtarjeta_master_consumo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_master_consumo_avg_6
    ,AVG(mtarjeta_master_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_master_descuentos_avg_6
    ,AVG(mtarjeta_visa_consumo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_visa_consumo_avg_6
    ,AVG(mtarjeta_visa_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtarjeta_visa_descuentos_avg_6
    ,AVG(mtransferencias_emitidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtransferencias_emitidas_avg_6
    ,AVG(mtransferencias_recibidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mtransferencias_recibidas_avg_6
    ,AVG(mttarjeta_master_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mttarjeta_master_debitos_automaticos_avg_6
    ,AVG(mttarjeta_visa_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS mttarjeta_visa_debitos_automaticos_avg_6
    ,AVG(tcallcenter, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS tcallcenter_avg_6
    ,AVG(tcuentas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS tcuentas_avg_6
    ,AVG(thomebanking, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS thomebanking_avg_6
    ,AVG(tmobile_app, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS tmobile_app_avg_6
    ,AVG(Visa_cadelantosefectivo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_cadelantosefectivo_avg_6
    ,AVG(Visa_cconsumos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_cconsumos_avg_6
    ,AVG(Visa_delinquency, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_delinquency_avg_6
    ,AVG(Visa_fechaalta, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_fechaalta_avg_6
    ,AVG(Visa_Finiciomora, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_Finiciomora_avg_6
    ,AVG(Visa_fultimo_cierre, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_fultimo_cierre_avg_6
    ,AVG(Visa_Fvencimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_Fvencimiento_avg_6
    ,AVG(Visa_madelantodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_madelantodolares_avg_6
    ,AVG(Visa_madelantopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_madelantopesos_avg_6
    ,AVG(Visa_mconsumosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mconsumosdolares_avg_6
    ,AVG(Visa_mconsumospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mconsumospesos_avg_6
    ,AVG(Visa_mconsumototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mconsumototal_avg_6
    ,AVG(Visa_mfinanciacion_limite, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mfinanciacion_limite_avg_6
    ,AVG(Visa_mlimitecompra, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mlimitecompra_avg_6
    ,AVG(Visa_mpagado, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagado_avg_6
    ,AVG(Visa_mpagominimo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagominimo_avg_6
    ,AVG(Visa_mpagosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagosdolares_avg_6
    ,AVG(Visa_mpagospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_mpagospesos_avg_6
    ,AVG(Visa_msaldodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_msaldodolares_avg_6
    ,AVG(Visa_msaldopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_msaldopesos_avg_6
    ,AVG(Visa_msaldototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_msaldototal_avg_6
    ,AVG(Visa_status, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS Visa_status_avg_6
FROM competencia_03
