SELECT
    *
    ,AVG(active_quarter, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS active_quarter_avg_3
    ,AVG(catm_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS catm_trx_avg_3
    ,AVG(catm_trx_other, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS catm_trx_other_avg_3
    ,AVG(ccaja_ahorro, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccaja_ahorro_avg_3
    ,AVG(ccaja_seguridad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccaja_seguridad_avg_3
    ,AVG(ccajas_consultas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccajas_consultas_avg_3
    ,AVG(ccajas_depositos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccajas_depositos_avg_3
    ,AVG(ccajas_extracciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccajas_extracciones_avg_3
    ,AVG(ccajas_otras, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccajas_otras_avg_3
    ,AVG(ccajas_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccajas_transacciones_avg_3
    ,AVG(ccajeros_propios_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccajeros_propios_descuentos_avg_3
    ,AVG(ccallcenter_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccallcenter_transacciones_avg_3
    ,AVG(ccheques_depositados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccheques_depositados_avg_3
    ,AVG(ccheques_depositados_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccheques_depositados_rechazados_avg_3
    ,AVG(ccheques_emitidos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccheques_emitidos_avg_3
    ,AVG(ccheques_emitidos_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccheques_emitidos_rechazados_avg_3
    ,AVG(ccomisiones_mantenimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccomisiones_mantenimiento_avg_3
    ,AVG(ccomisiones_otras, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccomisiones_otras_avg_3
    ,AVG(ccuenta_corriente, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccuenta_corriente_avg_3
    ,AVG(ccuenta_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ccuenta_debitos_automaticos_avg_3
    ,AVG(cdescubierto_preacordado, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cdescubierto_preacordado_avg_3
    ,AVG(cextraccion_autoservicio, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cextraccion_autoservicio_avg_3
    ,AVG(cforex, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cforex_avg_3
    ,AVG(cforex_buy, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cforex_buy_avg_3
    ,AVG(cforex_sell, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cforex_sell_avg_3
    ,AVG(chomebanking_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS chomebanking_transacciones_avg_3
    ,AVG(cinversion1, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cinversion1_avg_3
    ,AVG(cinversion2, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cinversion2_avg_3
    ,AVG(cliente_antiguedad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cliente_antiguedad_avg_3
    ,AVG(cliente_edad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cliente_edad_avg_3
    ,AVG(cliente_vip, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cliente_vip_avg_3
    ,AVG(cmobile_app_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cmobile_app_trx_avg_3
    ,AVG(cpagodeservicios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cpagodeservicios_avg_3
    ,AVG(cpagomiscuentas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cpagomiscuentas_avg_3
    ,AVG(cpayroll2_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cpayroll2_trx_avg_3
    ,AVG(cpayroll_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cpayroll_trx_avg_3
    ,AVG(cplazo_fijo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cplazo_fijo_avg_3
    ,AVG(cprestamos_hipotecarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cprestamos_hipotecarios_avg_3
    ,AVG(cprestamos_personales, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cprestamos_personales_avg_3
    ,AVG(cprestamos_prendarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cprestamos_prendarios_avg_3
    ,AVG(cproductos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cproductos_avg_3
    ,AVG(cseguro_accidentes_personales, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cseguro_accidentes_personales_avg_3
    ,AVG(cseguro_auto, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cseguro_auto_avg_3
    ,AVG(cseguro_vida, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cseguro_vida_avg_3
    ,AVG(cseguro_vivienda, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS cseguro_vivienda_avg_3
    ,AVG(ctarjeta_debito, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_debito_avg_3
    ,AVG(ctarjeta_debito_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_debito_transacciones_avg_3
    ,AVG(ctarjeta_master, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_master_avg_3
    ,AVG(ctarjeta_master_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_master_debitos_automaticos_avg_3
    ,AVG(ctarjeta_master_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_master_descuentos_avg_3
    ,AVG(ctarjeta_master_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_master_transacciones_avg_3
    ,AVG(ctarjeta_visa, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_avg_3
    ,AVG(ctarjeta_visa_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_debitos_automaticos_avg_3
    ,AVG(ctarjeta_visa_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_descuentos_avg_3
    ,AVG(ctarjeta_visa_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctarjeta_visa_transacciones_avg_3
    ,AVG(ctransferencias_emitidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctransferencias_emitidas_avg_3
    ,AVG(ctransferencias_recibidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctransferencias_recibidas_avg_3
    ,AVG(ctrx_quarter, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS ctrx_quarter_avg_3
    ,AVG(internet, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS internet_avg_3
    ,AVG(mactivos_margen, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mactivos_margen_avg_3
    ,AVG(Master_cadelantosefectivo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_cadelantosefectivo_avg_3
    ,AVG(Master_cconsumos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_cconsumos_avg_3
    ,AVG(Master_delinquency, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_delinquency_avg_3
    ,AVG(Master_fechaalta, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_fechaalta_avg_3
    ,AVG(Master_Finiciomora, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_Finiciomora_avg_3
    ,AVG(Master_fultimo_cierre, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_fultimo_cierre_avg_3
    ,AVG(Master_Fvencimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_Fvencimiento_avg_3
    ,AVG(Master_madelantodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_madelantodolares_avg_3
    ,AVG(Master_madelantopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_madelantopesos_avg_3
    ,AVG(Master_mconsumosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mconsumosdolares_avg_3
    ,AVG(Master_mconsumospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mconsumospesos_avg_3
    ,AVG(Master_mconsumototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mconsumototal_avg_3
    ,AVG(Master_mfinanciacion_limite, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mfinanciacion_limite_avg_3
    ,AVG(Master_mlimitecompra, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mlimitecompra_avg_3
    ,AVG(Master_mpagado, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mpagado_avg_3
    ,AVG(Master_mpagominimo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mpagominimo_avg_3
    ,AVG(Master_mpagosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mpagosdolares_avg_3
    ,AVG(Master_mpagospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_mpagospesos_avg_3
    ,AVG(Master_msaldodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_msaldodolares_avg_3
    ,AVG(Master_msaldopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_msaldopesos_avg_3
    ,AVG(Master_msaldototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_msaldototal_avg_3
    ,AVG(Master_status, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Master_status_avg_3
    ,AVG(matm, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS matm_avg_3
    ,AVG(matm_other, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS matm_other_avg_3
    ,AVG(mautoservicio, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mautoservicio_avg_3
    ,AVG(mcaja_ahorro, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_avg_3
    ,AVG(mcaja_ahorro_adicional, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_adicional_avg_3
    ,AVG(mcaja_ahorro_dolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcaja_ahorro_dolares_avg_3
    ,AVG(mcajeros_propios_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcajeros_propios_descuentos_avg_3
    ,AVG(mcheques_depositados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcheques_depositados_avg_3
    ,AVG(mcheques_depositados_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcheques_depositados_rechazados_avg_3
    ,AVG(mcheques_emitidos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcheques_emitidos_avg_3
    ,AVG(mcheques_emitidos_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcheques_emitidos_rechazados_avg_3
    ,AVG(mcomisiones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcomisiones_avg_3
    ,AVG(mcomisiones_mantenimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcomisiones_mantenimiento_avg_3
    ,AVG(mcomisiones_otras, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcomisiones_otras_avg_3
    ,AVG(mcuenta_corriente, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcuenta_corriente_avg_3
    ,AVG(mcuenta_corriente_adicional, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcuenta_corriente_adicional_avg_3
    ,AVG(mcuenta_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcuenta_debitos_automaticos_avg_3
    ,AVG(mcuentas_saldo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mcuentas_saldo_avg_3
    ,AVG(mextraccion_autoservicio, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mextraccion_autoservicio_avg_3
    ,AVG(mforex_buy, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mforex_buy_avg_3
    ,AVG(mforex_sell, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mforex_sell_avg_3
    ,AVG(minversion1_dolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS minversion1_dolares_avg_3
    ,AVG(minversion1_pesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS minversion1_pesos_avg_3
    ,AVG(minversion2, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS minversion2_avg_3
    ,AVG(mpagodeservicios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mpagodeservicios_avg_3
    ,AVG(mpagomiscuentas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mpagomiscuentas_avg_3
    ,AVG(mpasivos_margen, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mpasivos_margen_avg_3
    ,AVG(mpayroll, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mpayroll_avg_3
    ,AVG(mpayroll2, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mpayroll2_avg_3
    ,AVG(mplazo_fijo_dolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mplazo_fijo_dolares_avg_3
    ,AVG(mplazo_fijo_pesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mplazo_fijo_pesos_avg_3
    ,AVG(mprestamos_hipotecarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mprestamos_hipotecarios_avg_3
    ,AVG(mprestamos_personales, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mprestamos_personales_avg_3
    ,AVG(mprestamos_prendarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mprestamos_prendarios_avg_3
    ,AVG(mrentabilidad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mrentabilidad_avg_3
    ,AVG(mrentabilidad_annual, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mrentabilidad_annual_avg_3
    ,AVG(mtarjeta_master_consumo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mtarjeta_master_consumo_avg_3
    ,AVG(mtarjeta_master_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mtarjeta_master_descuentos_avg_3
    ,AVG(mtarjeta_visa_consumo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mtarjeta_visa_consumo_avg_3
    ,AVG(mtarjeta_visa_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mtarjeta_visa_descuentos_avg_3
    ,AVG(mtransferencias_emitidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mtransferencias_emitidas_avg_3
    ,AVG(mtransferencias_recibidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mtransferencias_recibidas_avg_3
    ,AVG(mttarjeta_master_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mttarjeta_master_debitos_automaticos_avg_3
    ,AVG(mttarjeta_visa_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS mttarjeta_visa_debitos_automaticos_avg_3
    ,AVG(tcallcenter, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS tcallcenter_avg_3
    ,AVG(tcuentas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS tcuentas_avg_3
    ,AVG(thomebanking, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS thomebanking_avg_3
    ,AVG(tmobile_app, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS tmobile_app_avg_3
    ,AVG(Visa_cadelantosefectivo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_cadelantosefectivo_avg_3
    ,AVG(Visa_cconsumos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_cconsumos_avg_3
    ,AVG(Visa_delinquency, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_delinquency_avg_3
    ,AVG(Visa_fechaalta, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_fechaalta_avg_3
    ,AVG(Visa_Finiciomora, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_Finiciomora_avg_3
    ,AVG(Visa_fultimo_cierre, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_fultimo_cierre_avg_3
    ,AVG(Visa_Fvencimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_Fvencimiento_avg_3
    ,AVG(Visa_madelantodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_madelantodolares_avg_3
    ,AVG(Visa_madelantopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_madelantopesos_avg_3
    ,AVG(Visa_mconsumosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mconsumosdolares_avg_3
    ,AVG(Visa_mconsumospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mconsumospesos_avg_3
    ,AVG(Visa_mconsumototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mconsumototal_avg_3
    ,AVG(Visa_mfinanciacion_limite, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mfinanciacion_limite_avg_3
    ,AVG(Visa_mlimitecompra, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mlimitecompra_avg_3
    ,AVG(Visa_mpagado, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mpagado_avg_3
    ,AVG(Visa_mpagominimo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mpagominimo_avg_3
    ,AVG(Visa_mpagosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mpagosdolares_avg_3
    ,AVG(Visa_mpagospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_mpagospesos_avg_3
    ,AVG(Visa_msaldodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_msaldodolares_avg_3
    ,AVG(Visa_msaldopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_msaldopesos_avg_3
    ,AVG(Visa_msaldototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_msaldototal_avg_3
    ,AVG(Visa_status, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC ROWS BETWEEN 3 PRECEDING AND CURRENT ROW) AS Visa_status_avg_3
FROM competencia_03
