SELECT
    *
    ,AVG(active_quarter) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_active_quarter
    ,AVG(cliente_vip) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cliente_vip
    ,AVG(internet) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_internet
    ,AVG(cliente_edad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cliente_edad
    ,AVG(cliente_antiguedad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cliente_antiguedad
    ,AVG(mrentabilidad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mrentabilidad
    ,AVG(mrentabilidad_annual) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mrentabilidad_annual
    ,AVG(mcomisiones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcomisiones
    ,AVG(mactivos_margen) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mactivos_margen
    ,AVG(mpasivos_margen) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mpasivos_margen
     ,AVG(cproductos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cproductos
     ,AVG(tcuentas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_tcuentas
     ,AVG(ccuenta_corriente) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccuenta_corriente
     ,AVG(mcuenta_corriente_adicional) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcuenta_corriente_adicional
     ,AVG(mcuenta_corriente) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcuenta_corriente
     ,AVG(ccaja_ahorro) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccaja_ahorro
     ,AVG(mcaja_ahorro) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcaja_ahorro
     ,AVG(mcaja_ahorro_adicional) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcaja_ahorro_adicional
     ,AVG(mcaja_ahorro_dolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcaja_ahorro_dolares
     ,AVG(cdescubierto_preacordado) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cdescubierto_preacordado
     ,AVG(mcuentas_saldo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcuentas_saldo
     ,AVG(ctarjeta_debito) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_debito
     ,AVG(ctarjeta_debito_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_debito_transacciones
     ,AVG(mautoservicio) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mautoservicio
     ,AVG(ctarjeta_visa) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_visa
     ,AVG(ctarjeta_visa_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_visa_transacciones
     ,AVG(mtarjeta_visa_consumo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mtarjeta_visa_consumo
     ,AVG(ctarjeta_master) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_master
     ,AVG(ctarjeta_master_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_master_transacciones
     ,AVG(mtarjeta_master_consumo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mtarjeta_master_consumo
     ,AVG(cprestamos_personales) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cprestamos_personales
     ,AVG(mprestamos_personales) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mprestamos_personales
     ,AVG(cprestamos_prendarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cprestamos_prendarios
     ,AVG(mprestamos_prendarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mprestamos_prendarios
     ,AVG(cprestamos_hipotecarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cprestamos_hipotecarios
     ,AVG(mprestamos_hipotecarios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mprestamos_hipotecarios
     ,AVG(cplazo_fijo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cplazo_fijo
     ,AVG(mplazo_fijo_dolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mplazo_fijo_dolares
     ,AVG(mplazo_fijo_pesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mplazo_fijo_pesos
     ,AVG(cinversion1) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cinversion1
     ,AVG(minversion1_pesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_minversion1_pesos
     ,AVG(minversion1_dolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_minversion1_dolares
     ,AVG(cinversion2) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cinversion2
     ,AVG(minversion2) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_minversion2
     ,AVG(cseguro_vida) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cseguro_vida
     ,AVG(cseguro_auto) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cseguro_auto
     ,AVG(cseguro_vivienda) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cseguro_vivienda
     ,AVG(cseguro_accidentes_personales) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cseguro_accidentes_personales
     ,AVG(ccaja_seguridad) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccaja_seguridad
     ,AVG(cpayroll_trx) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cpayroll_trx
     ,AVG(mpayroll) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mpayroll
     ,AVG(mpayroll2) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mpayroll2
     ,AVG(cpayroll2_trx) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cpayroll2_trx
     ,AVG(ccuenta_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccuenta_debitos_automaticos
     ,AVG(mcuenta_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcuenta_debitos_automaticos
     ,AVG(ctarjeta_visa_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_visa_debitos_automaticos
     ,AVG(mttarjeta_visa_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mttarjeta_visa_debitos_automaticos
     ,AVG(ctarjeta_master_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_master_debitos_automaticos
     ,AVG(mttarjeta_master_debitos_automaticos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mttarjeta_master_debitos_automaticos
     ,AVG(cpagodeservicios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cpagodeservicios
     ,AVG(mpagodeservicios) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mpagodeservicios
     ,AVG(cpagomiscuentas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cpagomiscuentas
     ,AVG(mpagomiscuentas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mpagomiscuentas
     ,AVG(ccajeros_propios_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccajeros_propios_descuentos
     ,AVG(mcajeros_propios_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcajeros_propios_descuentos
     ,AVG(ctarjeta_visa_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_visa_descuentos
     ,AVG(mtarjeta_visa_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mtarjeta_visa_descuentos
     ,AVG(ctarjeta_master_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctarjeta_master_descuentos
     ,AVG(mtarjeta_master_descuentos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mtarjeta_master_descuentos
     ,AVG(ccomisiones_mantenimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccomisiones_mantenimiento
     ,AVG(mcomisiones_mantenimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcomisiones_mantenimiento
     ,AVG(ccomisiones_otras) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccomisiones_otras
     ,AVG(mcomisiones_otras) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcomisiones_otras
     ,AVG(cforex) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cforex
     ,AVG(cforex_buy) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cforex_buy
     ,AVG(mforex_buy) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mforex_buy
     ,AVG(cforex_sell) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cforex_sell
     ,AVG(mforex_sell) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mforex_sell
     ,AVG(ctransferencias_recibidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctransferencias_recibidas
     ,AVG(mtransferencias_recibidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mtransferencias_recibidas
     ,AVG(ctransferencias_emitidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctransferencias_emitidas
     ,AVG(mtransferencias_emitidas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mtransferencias_emitidas
     ,AVG(cextraccion_autoservicio) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_cextraccion_autoservicio
     ,AVG(mextraccion_autoservicio) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mextraccion_autoservicio
     ,AVG(ccheques_depositados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccheques_depositados
     ,AVG(mcheques_depositados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcheques_depositados
     ,AVG(ccheques_emitidos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccheques_emitidos
     ,AVG(mcheques_emitidos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcheques_emitidos
     ,AVG(ccheques_depositados_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccheques_depositados_rechazados
     ,AVG(mcheques_depositados_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcheques_depositados_rechazados
     ,AVG(ccheques_emitidos_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccheques_emitidos_rechazados
     ,AVG(mcheques_emitidos_rechazados) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_mcheques_emitidos_rechazados
     ,AVG(tcallcenter) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_tcallcenter
     ,AVG(ccallcenter_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccallcenter_transacciones
     ,AVG(thomebanking) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_thomebanking
     ,AVG(chomebanking_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_chomebanking_transacciones
     ,AVG(ccajas_transacciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccajas_transacciones
     ,AVG(ccajas_consultas) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccajas_consultas
     ,AVG(ccajas_depositos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccajas_depositos
     ,AVG(ccajas_extracciones) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccajas_extracciones
     ,AVG(ccajas_otras) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ccajas_otras
     ,AVG(catm_trx) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_catm_trx
     ,AVG(matm) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_matm
     ,AVG(catm_trx_other) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_catm_trx_other
     ,AVG(matm_other) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_matm_other
     ,AVG(ctrx_quarter) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_ctrx_quarter
     ,AVG(Master_delinquency) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_delinquency
     ,AVG(Master_status) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_status
     ,AVG(Master_mfinanciacion_limite) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mfinanciacion_limite
     ,AVG(Master_Fvencimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_Fvencimiento
     ,AVG(Master_Finiciomora) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_Finiciomora
     ,AVG(Master_msaldototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_msaldototal
     ,AVG(Master_msaldopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_msaldopesos
     ,AVG(Master_msaldodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_msaldodolares
     ,AVG(Master_mconsumospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mconsumospesos
     ,AVG(Master_mconsumosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mconsumosdolares
     ,AVG(Master_mlimitecompra) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mlimitecompra
     ,AVG(Master_madelantopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_madelantopesos
     ,AVG(Master_madelantodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_madelantodolares
     ,AVG(Master_fultimo_cierre) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_fultimo_cierre
     ,AVG(Master_mpagado) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mpagado
     ,AVG(Master_mpagospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mpagospesos
     ,AVG(Master_mpagosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mpagosdolares
     ,AVG(Master_fechaalta) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_fechaalta
     ,AVG(Master_mconsumototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mconsumototal
     ,AVG(Master_cconsumos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_cconsumos
     ,AVG(Master_cadelantosefectivo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_cadelantosefectivo
     ,AVG(Master_mpagominimo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Master_mpagominimo
     ,AVG(Visa_delinquency) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_delinquency
     ,AVG(Visa_status) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_status
     ,AVG(Visa_mfinanciacion_limite) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mfinanciacion_limite
     ,AVG(Visa_Fvencimiento) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_Fvencimiento
     ,AVG(Visa_Finiciomora) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_Finiciomora
     ,AVG(Visa_msaldototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_msaldototal
     ,AVG(Visa_msaldopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_msaldopesos
     ,AVG(Visa_msaldodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_msaldodolares
     ,AVG(Visa_mconsumospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mconsumospesos
     ,AVG(Visa_mconsumosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mconsumosdolares
     ,AVG(Visa_mlimitecompra) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mlimitecompra
     ,AVG(Visa_madelantopesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_madelantopesos
     ,AVG(Visa_madelantodolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_madelantodolares
     ,AVG(Visa_fultimo_cierre) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_fultimo_cierre
     ,AVG(Visa_mpagado) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mpagado
     ,AVG(Visa_mpagospesos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mpagospesos
     ,AVG(Visa_mpagosdolares) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mpagosdolares
     ,AVG(Visa_fechaalta) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_fechaalta
     ,AVG(Visa_mconsumototal) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mconsumototal
     ,AVG(Visa_cconsumos) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_cconsumos
     ,AVG(Visa_cadelantosefectivo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_cadelantosefectivo
     ,AVG(Visa_mpagominimo) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS avg_6_Visa_mpagominimo
FROM competencia_03
